_target_: azureml.acft.image.components.olympus.core.ModuleDatasets    
test:
  # _target_: torch.utils.data.ConcatDataset
  # datasets:
  - _target_: src.datasets.biomedparse_dataset_3D.BiomedParseDataset3D 
    _partial_: True
    root_dir: ${mounts.external}/data/test